import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import styles from './layout.module.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'HSS',
  description: 'Generated by codit 3rd team',
  viewport: 'width=device-width, initial-scale=1.0'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      
      <body className={inter.className}>
        {/** 헤더 */}
        <header>
          <label className={styles.header_content}>HSS</label>
          <div className={styles.header_bar}/>
        </header>
        {children}
        {/** 푸터 */}
        <footer>
        <label className={styles.footer}>
        <a href="https://kr.freepik.com/free-photo/artistic-blurry-colorful-wallpaper-background_62086882.htm#page=2&query=%EB%B0%B0%EA%B2%BD&position=29&from_view=keyword&track=sph">작가 user3802032</a> 출처 Freepik
        </label>
        <label>
          Copyright ⓒ 2023 simsimhan73. All Rights Reserved.

        </label>
      </footer>
      </body>
      
      
    </html>
  )
}
